# Generated by Django 4.1.5 on 2023-01-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='titel',
            new_name='title',
        ),
    ]
